### ISSUE TITLE
failed to build github.com/stackb/grpc.js/example/routeguide/client:bundle

### ISSUE THREAD

**Issue by manazhao** [stackb/rules_proto#101]
I go the following error when running the following command,
bazel build github.com/stackb/grpc.js/example/routeguide/client:bundle

ERROR: /home/manazhao/.cache/bazel/_bazel_manazhao/cebe4156e94c57479031319b57bea141/external/io_bazel_rules_closure/java/io/bazel/rules/closure/BUILD:37:1: Building external/io_bazel_rules_closure/java/io/bazel/rules/closure/libtarjan.jar (1 source file) and running annotation processors (AutoAnnotationProcessor, AutoOneOfProcessor, AutoValueProcessor) failed: Worker process did not return a WorkResponse:

---8<---8<--- Start of log, file at /home/manazhao/.cache/bazel/_bazel_manazhao/cebe4156e94c57479031319b57bea141/bazel-workers/worker-4-Javac.log ---8<---8<---
Exception in thread "main" java.lang.UnsupportedClassVersionError: javax/lang/model/element/TypeElement has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 54.0
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
        at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
        at java.base/java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(Unknown Source)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassInModuleOrNull(Unknown Source)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(Unknown Source)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(Unknown Source)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(Unknown Source)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at com.google.devtools.build.buildjar.BazelJavaBuilder.parse(BazelJavaBuilder.java:137)
        at com.google.devtools.build.buildjar.BazelJavaBuilder.processRequest(BazelJavaBuilder.java:91)
        at com.google.devtools.build.buildjar.BazelJavaBuilder.runPersistentWorker(BazelJavaBuilder.java:68)
        at com.google.devtools.build.buildjar.BazelJavaBuilder.main(BazelJavaBuilder.java:46)
---8<---8<--- End of log ---8<---8<---
Target //github.com/stackb/grpc.js/example/routeguide/client:bundle failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2.602s, Critical Path: 1.82s
INFO: 0 processes.

bazel version: 0.27.0
jdk version: OpenJDK Runtime Environment (build 11.0.2+7-LTS) by Azul Systems, Inc.

**Comment by pcj** [comment]
Have not attempted bazel 0.27 yet, but this error does not look related to the example per se, probably should file this on bazel itself or rules_closure (which is where the error is, compiling `io_bazel_rules_closure/java/io/bazel/rules/closure/libtarjan.jar`)

**Comment by pcj** [comment]
Closing stale PRs and issue, please reopen new one if desired.
