### ISSUE TITLE
http_archive must be in the WORKSPACE file

### ISSUE THREAD

**Issue by basavaraj29** [stackb/rules_proto#102]
### Issue
I'm trying to build a `java_proto_library` target. It fails with the following error
```
ERROR: /home/basav/dir/BUILD:6:1: Traceback (most recent call last):
	File "/home/basav/dir/BUILD", line 6
		java_proto_library(name = "target", ..."])
	File "/root/.cache/bazel/_bazel_root/<>/external/build_stack_rules_proto/java/deps.bzl", line 62, in java_proto_library
		java_proto_compile(**kwargs)
	File "/root/.cache/bazel/_bazel_root/<>/external/build_stack_rules_proto/java/deps.bzl", line 55, in java_proto_compile
		protobuf(**kwargs)
	File "/root/.cache/bazel/_bazel_root/<>/external/build_stack_rules_proto/protobuf/deps.bzl", line 12, in protobuf
		com_github_madler_zlib(**kwargs)
	File "/root/.cache/bazel/_bazel_root/<>/external/build_stack_rules_proto/deps.bzl", line 123, in com_github_madler_zlib
		http_archive(name = "com_github_madler_zlib", b..., <3 more arguments>)
http_archive must be in the WORKSPACE file (used by //dir:com_github_madler_zlib)
```

### bazel version
```
0.23.0
```
### WORKSPACE
```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
    name = "build_stack_rules_proto",
    urls = ["https://github.com/stackb/rules_proto/archive/b93b544f851fdcd3fc5c3d47aee3b7ca158a8841.tar.gz"],
    sha256 = "c62f0b442e82a6152fcd5b1c0b7c4028233a9e314078952b6b04253421d56d61",
    strip_prefix = "rules_proto-b93b544f851fdcd3fc5c3d47aee3b7ca158a8841",
)

load("@build_stack_rules_proto//java:deps.bzl", "java_proto_compile")
java_proto_compile()

load("@build_stack_rules_proto//java:deps.bzl", "java_grpc_compile")
java_grpc_compile()

load("@build_stack_rules_proto//java:deps.bzl", "java_proto_library")
java_proto_library()

load("@build_stack_rules_proto//python:deps.bzl", "python_proto_library")
python_proto_library()

load("@io_bazel_rules_python//python:pip.bzl", "pip_import", "pip_repositories")
pip_repositories()

pip_import(
    name = "protobuf_py_deps",
    requirements = "@build_stack_rules_proto//python/requirements:protobuf.txt",
)

load("@protobuf_py_deps//:requirements.bzl", protobuf_pip_install = "pip_install")
protobuf_pip_install()

load("@build_stack_rules_proto//:deps.bzl", "io_grpc_grpc_java")
io_grpc_grpc_java()

load("@io_grpc_grpc_java//:repositories.bzl", "grpc_java_repositories")
grpc_java_repositories(omit_com_google_protobuf = True)

load("@build_stack_rules_proto//java:deps.bzl", "java_grpc_library")
java_grpc_library()
```
### BUILD file
```
package(default_visibility = ["//visibility:public"])
load("@build_stack_rules_proto//java:deps.bzl", "java_proto_library")

java_proto_library(
    name = "target",
    deps = [
        "test.proto",
    ],
)
```

**Comment by markisus** [comment]
I am also seeing this. How did you resolve it?

**Comment by markisus** [comment]
I was including the deps.bzl file instead of the correct file.

e.g., in the BUILD file,
`load("@build_stack_rules_proto//python:deps.bzl", "python_proto_library")` is incorrect and should be replaced by `load("@build_stack_rules_proto//python:python_proto_library.bzl", "python_proto_library")`
