### ISSUE TITLE
Do python rules work with python3?

### ISSUE THREAD

**Issue by realazthat** [stackb/rules_proto#105]
I spent a couple of hours trying to get the python rules to work with python3, and due to a dependency on enum34 library, it won't work.

## My environment:

```bash
~/projects/rules_proto/example/python/python_grpc_library$ python3 --version
Python 3.6.8

~/projects/rules_proto/example/python/python_grpc_library$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic
```

## Reproducing the issue

* Fresh clone of master

New file `server.py`:

```
`/rules_proto/example/python/python_grpc_library/server.py:`

```python
import platform
print(platform.python_version())
```

Edit `BUILD.bazel`:

`/rules_proto/example/python/python_grpc_library/BUILD.bazel:`

```python
load("@build_stack_rules_proto//python:python_grpc_library.bzl", "python_grpc_library")

python_grpc_library(
    name = "greeter_python_library",
    deps = ["@build_stack_rules_proto//example/proto:greeter_grpc"],
)

py_binary(
    name = "server",
    srcs = ["server.py"],
    deps = [":greeter_python_library"],
)
```

Then run:

```bash
~/projects/rules_proto/example/python/python_grpc_library$ bazel run :server
Loading: 
Loading: 0 packages loaded
Analyzing: target //:server (1 packages loaded, 0 targets configured)
INFO: Analyzed target //:server (1 packages loaded, 4 targets configured).
INFO: Found 1 target...
[0 / 1] [Prepa] BazelWorkspaceStatusAction stable-status.txt
Target //:server up-to-date:
  bazel-bin/server
INFO: Elapsed time: 0.667s, Critical Path: 0.08s
INFO: 0 processes.
INFO: Build completed successfully, 4 total actions
INFO: Running command line: bazel-bin/server
INFO: Build completed successfully, 4 total actions
Traceback (most recent call last):
  File "/home/realz/.cache/bazel/_bazel_realz/3809334db000da46ec72d728a0e8e403/execroot/__main__/bazel-out/k8-fastbuild/bin/server.runfiles/__main__/server.py", line 3, in <module>
    import platform
  File "/usr/lib/python3.6/platform.py", line 116, in <module>
    import sys, os, re, subprocess
  File "/usr/lib/python3.6/re.py", line 142, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 53, in apport_excepthook
    if not enabled():
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 24, in enabled
    import re
  File "/usr/lib/python3.6/re.py", line 142, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'

Original exception was:
Traceback (most recent call last):
  File "/home/realz/.cache/bazel/_bazel_realz/3809334db000da46ec72d728a0e8e403/execroot/__main__/bazel-out/k8-fastbuild/bin/server.runfiles/__main__/server.py", line 3, in <module>
    import platform
  File "/usr/lib/python3.6/platform.py", line 116, in <module>
    import sys, os, re, subprocess
  File "/usr/lib/python3.6/re.py", line 142, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
```

If I remove the dependency on `:greeter_python_library`, then I get this:

```bash
~/projects/rules_proto/example/python/python_grpc_library$ bazel run :server
Loading: 
Loading: 0 packages loaded
Analyzing: target //:server (1 packages loaded, 0 targets configured)
INFO: Analyzed target //:server (1 packages loaded, 2 targets configured).
INFO: Found 1 target...
[0 / 1] [Prepa] BazelWorkspaceStatusAction stable-status.txt
Target //:server up-to-date:
  bazel-bin/server
INFO: Elapsed time: 0.461s, Critical Path: 0.03s
INFO: 0 processes.
INFO: Build completed successfully, 4 total actions
INFO: Running command line: bazel-bin/server
INFO: Build completed successfully, 4 total actions
3.6.8
```

From googling around, it appears that simply having a dependency on enum34 in python > 3.6 makes everything break, and grpc for python used by rules_proto seems to have this dependency.

### Attempted using python 3.5

Added to `/rules_proto/example/python/python_grpc_library/BUILD.bazel`:
```python

py_runtime(
    name = "python-3.5",
    files = [],
    interpreter_path = "/usr/bin/python3.5",
    python_version = 'PY3',
)
```

However, when actually trying to import things in `server.py` it doesn't work.

`/rules_proto/example/python/python_grpc_library/server.py`:

```python

from example.proto import greeter_pb2
from example.proto import greeter_pb2_grpc

import platform
print(platform.python_version())
```

```bash
~/projects/rules_proto/example/python/python_grpc_library$ bazel clean --expunge
~/projects/rules_proto/example/python/python_grpc_library$ bazel run :server --python_top=:python-3.4 --incompatible_use_python_toolchains=false

Traceback (most recent call last):
  File "/home/realz/.cache/bazel/_bazel_realz/3809334db000da46ec72d728a0e8e403/execroot/__main__/bazel-out/k8-fastbuild/bin/server.runfiles/__main__/server.py", line 3, in <module>
    from example.proto import greeter_pb2_grpc
  File "/home/realz/.cache/bazel/_bazel_realz/3809334db000da46ec72d728a0e8e403/execroot/__main__/bazel-out/k8-fastbuild/bin/server.runfiles/build_stack_rules_proto/example/proto/greeter_pb2_grpc.py", line 2, in <module>
    import grpc
  File "/home/realz/.cache/bazel/_bazel_realz/3809334db000da46ec72d728a0e8e403/execroot/__main__/bazel-out/k8-fastbuild/bin/server.runfiles/pypi__grpcio_1_20_0/grpc/__init__.py", line 23, in <module>
    from grpc._cython import cygrpc as _cygrpc
ImportError: /home/realz/.cache/bazel/_bazel_realz/3809334db000da46ec72d728a0e8e403/execroot/__main__/bazel-out/k8-fastbuild/bin/server.runfiles/pypi__grpcio_1_20_0/grpc/_cython/cygrpc.so: undefined symbol: _Py_ZeroStruct
```

I couldn't find much about this error online w.r.t bazel. All indications are that something is mixing between python 2.x and python 3.x.

### Attempted using python 3.8

I have also tried using python 3.8, and that gets the enum34 issue again.

### Attempted using virtualenv

With python 3.5:

```bash
Traceback (most recent call last):
  File "/home/realz/.cache/bazel/_bazel_realz/3809334db000da46ec72d728a0e8e403/execroot/__main__/bazel-out/k8-fastbuild/bin/server.runfiles/__main__/server.py", line 3, in <module>
    from example.proto import greeter_pb2_grpc
  File "/home/realz/.cache/bazel/_bazel_realz/3809334db000da46ec72d728a0e8e403/execroot/__main__/bazel-out/k8-fastbuild/bin/server.runfiles/build_stack_rules_proto/example/proto/greeter_pb2_grpc.py", line 2, in <module>
    import grpc
  File "/home/realz/.cache/bazel/_bazel_realz/3809334db000da46ec72d728a0e8e403/execroot/__main__/bazel-out/k8-fastbuild/bin/server.runfiles/pypi__grpcio_1_20_0/grpc/__init__.py", line 23, in <module>
    from grpc._cython import cygrpc as _cygrpc
ImportError: cannot import name 'cygrpc'
```

With python 3.6: it works.

## Conclusion

Is this expected behavior? Do I have to run bazel in virtualenv? I wish there was something in the documentation that could have saved me some time here.

**Comment by aaliddell** [comment]
This is due to the underlying [`rules_python`](https://github.com/bazelbuild/rules_python) not having a simple mechanism to disambiguate pip requirements between python 2 and 3, despite there being a number of open issues regarding this. Therefore, when using `python_grpc_library`, you are getting the default Python 2 grpcio dependencies that are not suitable for Python 3.

**Comment by pierreis** [comment]
Is there anything I can do to help push this issue forward? I cannot find a proper solution (or workaround) to this at the moment.

**Comment by kolotaev** [comment]
Hi,
We're experiencing the same issue with `AttributeError: module 'enum' has no attribute 'IntFlag'` on Python 3.6.8 and 3.7.4.

In this state the rules are completely unusable for Python 3.
Is there any workaround?

**Comment by johnpaulett** [comment]
rules_python recently added a `pip3_import` that appears to fix this issue.

https://github.com/bazelbuild/rules_python/pull/256

**Comment by pcj** [comment]
Closing stale PRs and issue, please reopen new one if desired.
