### ISSUE TITLE
Broken on Bazel CI

### ISSUE THREAD

**Issue by laszlocsomor** [stackb/rules_proto#132]
The "stackb/rules_proto" pipeline is broken on Bazel CI:

https://buildkite.com/bazel/stackb-rules-proto/builds/383#fe269744-67d2-4e5a-b080-5528f4f20e12

```

ERROR: Unrecognized option: --incompatible_no_transitive_loads=false
--
  | Traceback (most recent call last):
  | File "bazelci.py", line 2887, in <module>
  | sys.exit(main())
  | File "bazelci.py", line 2867, in main
  | bazel_version=task_config.get("bazel") or configs.get("bazel"),
  | File "bazelci.py", line 831, in execute_commands
  | bazel_version = print_bazel_version_info(bazel_binary, platform)
  | File "bazelci.py", line 1048, in print_bazel_version_info
  | + ["--nomaster_bazelrc", "--bazelrc=/dev/null", "info"]
  | File "bazelci.py", line 1689, in execute_command
  | args, shell=shell, check=fail_if_nonzero, env=os.environ, cwd=cwd
  | File "/usr/local/lib/python3.6/subprocess.py", line 438, in run
  | output=stdout, stderr=stderr)
  | subprocess.CalledProcessError: Command '['bazel', '--nomaster_bazelrc', '--bazelrc=/dev/null', 'info']' returned non-zero exit status 2.
```

**Comment by pcj** [comment]
Closing stale PRs and issues, please reopen new one if desired.
