### ISSUE TITLE
Mysterious failure with Python proto build

### ISSUE THREAD

**Issue by sgammon** [stackb/rules_proto#148]
I have a macro in my Bazel codebase which wraps each proto definition. After amending the macro to generate Python proto libraries (in addition to regular `proto_library`, closure, and Java targets so far), I get the following error:

```
FAILED: Build did NOT complete successfully (8 packages loaded)
    currently loading: js ... (9 packages)
    Fetching @rules_pkg; fetching
    Fetching @npm_bazel_jasmine; fetching
    Fetching @bazel_common; fetching
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node 'PACKAGE:gust/page' (requested by nodes 'PACKAGE_ERROR_MESSAGE:gust/page')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:515)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: 'repo_mapping' may only be used in the //external package
	at com.google.devtools.build.lib.packages.Package.finishInit(Package.java:410)
	at com.google.devtools.build.lib.packages.Package.access$2900(Package.java:80)
	at com.google.devtools.build.lib.packages.Package$Builder.finishBuild(Package.java:1543)
	at com.google.devtools.build.lib.skyframe.PackageFunction.compute(PackageFunction.java:539)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:438)
	... 4 more
java.lang.RuntimeException: Unrecoverable error while evaluating node 'PACKAGE:gust/page' (requested by nodes 'PACKAGE_ERROR_MESSAGE:gust/page')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:515)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: 'repo_mapping' may only be used in the //external package
	at com.google.devtools.build.lib.packages.Package.finishInit(Package.java:410)
```

The failure is bad enough that the Bazel worker crashes entirely.

It seems specifically related to `stackb/rules_proto`'s Python support. I tried the Swift rules and they work fine, so it seems like it can't be a bug in the shared utilities between the two.

**Comment by joesonw** [comment]
Same here for `gateway_grpc_library`. I suspect it's with Bazel 3.0.0 issue

@sgammon are you using bazel 3?

**Comment by pcj** [comment]
Closing stale PRs and issues, please reopen new one if desired.
