### ISSUE TITLE
android_proto_library fails with latest Bazel daily build

### ISSUE THREAD

**Issue by paladine** [stackb/rules_proto#20]
Attempting to use android_proto_library fails with the following error, related to the version of protobuf defined in deps.bzl

```
ERROR:` /home/tcj/.cache/bazel/_bazel_tcj/86df34957ac88767728a08679bac58bf/external/com_google_protobuf_lite/BUILD:538:1: Traceback (most recent call last):
        File "/home/tcj/.cache/bazel/_bazel_tcj/86df34957ac88767728a08679bac58bf/external/com_google_protobuf_lite/BUILD", line 538
                internal_gen_well_known_protos_java(srcs = WELL_KNOWN_PROTOS)
        File "/home/tcj/.cache/bazel/_bazel_tcj/86df34957ac88767728a08679bac58bf/external/com_google_protobuf_lite/protobuf.bzl", line 266, in internal_gen_well_known_protos_java
                Label(("%s//protobuf_java" % REPOSITOR...))
        File "/home/tcj/.cache/bazel/_bazel_tcj/86df34957ac88767728a08679bac58bf/external/com_google_protobuf_lite/protobuf.bzl", line 266, in Label
                REPOSITORY_NAME
builtin variable 'REPOSITORY_NAME' is referenced before assignment.
ERROR: /home/tcj/.cache/bazel/_bazel_tcj/86df34957ac88767728a08679bac58bf/external/com_google_protobuf_lite/BUILD:593:1: Target '@com_google_protobuf_lite//:android' contains an error and its package is in error and referenced by '@com_google_protobuf_lite//:protoc_gen_javalite'
ERROR: /home/tcj/.cache/bazel/_bazel_tcj/86df34957ac88767728a08679bac58bf/external/build_stack_rules_proto/android/BUILD.bazel:3:1: Target '@com_google_protobuf_lite//:protoc_gen_javalite' contains an error and its package is in error and referenced by '@build_stack_rules_proto//android:javalite'
ERROR: Analysis of target '//euchre:android_euchre_proto' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.048s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (2 packages loaded, 2 targets conf\
igured)
```

It appears the issue has been fixed in the protobuf git repo, so updating to the latest commit should in theory resolve the issue - https://github.com/protocolbuffers/protobuf/commit/384989534b2246d413dbcd750744faab2607b516

I can see how to update the commit hash in deps.bzl, but I'm not sure how to update the sha256.

**Comment by pcj** [comment]
One can either download the artifact directly and run something like `shasum -a256`, or make a trivial change (switch an `a` to a `b`) in the one listed in the `deps.bzl` retry the build and wait for bazel to complain about the hash being different, then use the printed actual value.
