### ISSUE TITLE
rules_proto & rules_go problems / general dependency problems

### ISSUE THREAD

**Issue by joelMuehlena** [stackb/rules_proto#309]
Hi,
I'm trying to get this running in my project. If I follow the examples and declare the Bazel depenencies like this:

1. Proto
2. Go
3. Gazelle

I get the following error: 

```
ERROR: Traceback (most recent call last):
        File "/home/joel/jm-web-dev/services-mono/WORKSPACE.bazel", line 117, column 23, in <toplevel>
                go_register_toolchains(version = "1.19.5")
        File "/home/joel/.cache/bazel/_bazel_joel/7f2e3502f2ff89677e0156ae86916e48/external/io_bazel_rules_go/go/private/sdk.bzl", line 241, column 5, in go_register_toolchains
                def go_register_toolchains(go_version = None, nogo = None):
Error: go_register_toolchains() got unexpected keyword argument: version (did you mean 'go_version'?)
```

When I switch them to have go and gazelle first everything compiles, until it comes to the go project which actually uses the proto stuff. So it seems like any kind of problems with the go toolchain selection.

The error after switching to 1. go 2. gazelle 3. proto is the following, which I guess seems like maybe an outdated version of go grpc:

```
ERROR: /home/joel/.cache/bazel/_bazel_joel/7f2e3502f2ff89677e0156ae86916e48/external/org_golang_google_grpc/reflection/BUILD.bazel:3:11: GoCompilePkg external/org_golang_google_grpc/reflection/reflection.a failed: (Exit 1): builder failed: error executing command (from target @org_golang_google_grpc//reflection:reflection) bazel-out/k8-opt-exec-2B5CBBC6/bin/external/go_sdk/builder compilepkg -sdk external/go_sdk -installsuffix linux_amd64 -src external/org_golang_google_grpc/reflection/serverreflection.go -embedroot '' ... (remaining 34 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
external/org_golang_google_grpc/reflection/serverreflection.go:66:37: cannot use s (variable of type GRPCServer) as type *grpc.Server in argument to rpb.RegisterServerReflectionServer:
        need type assertion
compilepkg: error running subcommand external/go_sdk/pkg/tool/linux_amd64/compile: exit status 2
Target //api/user/cmd:cmd failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.977s, Critical Path: 0.07s
INFO: 3 processes: 3 internal.
```

In no configuration I get it to run my application. Also if I not manually add `rules_pkg` to my workspace file (at the very top) I also get errors.

BUILD.bazel (root level)
```
load("@bazel_gazelle//:def.bzl", "gazelle", "gazelle_binary")
load("@npm//@bazel/typescript:index.bzl", "ts_config")

# gazelle:proto_rule proto_compile implementation stackb:rules_proto:proto_compile

## Go ##
# gazelle:proto_plugin protoc-gen-go implementation golang:protobuf:protoc-gen-go
# gazelle:proto_rule proto_go_library implementation stackb:rules_proto:proto_go_library
# gazelle:proto_rule proto_go_library deps @org_golang_google_protobuf//reflect/protoreflect
# gazelle:proto_rule proto_go_library deps @org_golang_google_protobuf//runtime/protoimpl
# gazelle:proto_rule proto_go_library visibility //visibility:public
# gazelle:proto_language go plugin protoc-gen-go
# gazelle:proto_language go rule proto_compile

gazelle_binary(
    name = "gazelle-protobuf",
    languages = [
        "@bazel_gazelle//language/go",
        "@bazel_gazelle//language/proto",
        # must be after the proto extension (order matters)
        "@build_stack_rules_proto//language/protobuf",
    ],
    visibility = ["//visibility:public"],
)

gazelle(
    name = "update_go_deps",
    args = [
        "-from_file=go.sum",
        "-to_macro=repositories.bzl%go_repositories",
        "-build_file_proto_mode=disable_global",
        "-prune=true",
    ],
    command = "update-repos",
)

# gazelle:prefix gitlab.com/joelMuehlena/jm-web-monorepo
gazelle(
    name = "gazelle",
    gazelle = ":gazelle-protobuf",
)

ts_config(
    name = "tsconfig_base",
    src = "tsconfig.base.json",
    visibility = ["//visibility:public"],
)
```

WORKSPACE.bazel
```
workspace(
    name = "joel-muehlena-website",
)

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

#################################
# rules_pkg (required by proto) #
################################

http_archive(
    name = "rules_pkg",
    sha256 = "eea0f59c28a9241156a47d7a8e32db9122f3d50b505fae0f33de6ce4d9b61834",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_pkg/releases/download/0.8.0/rules_pkg-0.8.0.tar.gz",
        "https://github.com/bazelbuild/rules_pkg/releases/download/0.8.0/rules_pkg-0.8.0.tar.gz",
    ],
)

load("@rules_pkg//:deps.bzl", "rules_pkg_dependencies")

rules_pkg_dependencies()

#################################
#            Skylib            #
################################

http_archive(
    name = "bazel_skylib",
    sha256 = "74d544d96f4a5bb630d465ca8bbcfe231e3594e5aae57e1edbf17a6eb3ca2506",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/releases/download/1.3.0/bazel-skylib-1.3.0.tar.gz",
        "https://github.com/bazelbuild/bazel-skylib/releases/download/1.3.0/bazel-skylib-1.3.0.tar.gz",
    ],
)

load("@bazel_skylib//:workspace.bzl", "bazel_skylib_workspace")

bazel_skylib_workspace()

#################################
#            Docker            #
################################

http_archive(
    name = "io_bazel_rules_docker",
    sha256 = "b1e80761a8a8243d03ebca8845e9cc1ba6c82ce7c5179ce2b295cd36f7e394bf",
    urls = ["https://github.com/bazelbuild/rules_docker/releases/download/v0.25.0/rules_docker-v0.25.0.tar.gz"],
)

load(
    "@io_bazel_rules_docker//repositories:repositories.bzl",
    container_repositories = "repositories",
)

container_repositories()

################################
#           Proto              #
################################

http_archive(
    name = "build_stack_rules_proto",
    sha256 = "ac7e2966a78660e83e1ba84a06db6eda9a7659a841b6a7fd93028cd8757afbfb",
    strip_prefix = "rules_proto-2.0.1",
    urls = ["https://github.com/stackb/rules_proto/archive/v2.0.1.tar.gz"],
)

register_toolchains("@build_stack_rules_proto//toolchain:standard")

load("@build_stack_rules_proto//deps:core_deps.bzl", "core_deps")
load("@build_stack_rules_proto//deps:protobuf_core_deps.bzl", "protobuf_core_deps")
load("@build_stack_rules_proto//deps:grpc_core_deps.bzl", "grpc_core_deps")

core_deps()

protobuf_core_deps()

grpc_core_deps()

#################################
#           Proto Go           #
################################

load("@build_stack_rules_proto//deps:go_core_deps.bzl", "go_core_deps")

go_core_deps()

#################################
#            Go                #
################################

http_archive(
    name = "io_bazel_rules_go",
    sha256 = "19ef30b21eae581177e0028f6f4b1f54c66467017be33d211ab6fc81da01ea4d",
    urls = [
        "https://github.com/bazelbuild/rules_go/releases/download/v0.38.0/rules_go-v0.38.0.zip",
        #"https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.38.0/rules_go-v0.38.0.zip",
    ],
)

http_archive(
    name = "bazel_gazelle",
    sha256 = "ecba0f04f96b4960a5b250c8e8eeec42281035970aa8852dda73098274d14a1d",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-gazelle/releases/download/v0.29.0/bazel-gazelle-v0.29.0.tar.gz",
        "https://github.com/bazelbuild/bazel-gazelle/releases/download/v0.29.0/bazel-gazelle-v0.29.0.tar.gz",
    ],
)

load("@io_bazel_rules_go//go:deps.bzl", "go_register_toolchains", "go_rules_dependencies")

go_rules_dependencies()

go_register_toolchains(version = "1.19.5")

load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies")
load("//:repositories.bzl", "go_repositories")

gazelle_dependencies(go_repository_default_config = "//:WORKSPACE.bazel")

# gazelle:repository_macro repositories.bzl%go_repositories
go_repositories()

load("@build_stack_rules_proto//:go_deps.bzl", "gazelle_protobuf_extension_go_deps")

gazelle_protobuf_extension_go_deps()

#################################
#          Core gRPC           #
################################
load(
    "@com_github_grpc_grpc//bazel:grpc_deps.bzl",
    "grpc_deps",
)

grpc_deps()

#################################
#          Yarn/Npm/JS         #
################################

http_archive(
    name = "build_bazel_rules_nodejs",
    sha256 = "dcc55f810142b6cf46a44d0180a5a7fb923c04a5061e2e8d8eb05ccccc60864b",
    urls = ["https://github.com/bazelbuild/rules_nodejs/releases/download/5.8.0/rules_nodejs-5.8.0.tar.gz"],
)

load("@build_bazel_rules_nodejs//:repositories.bzl", "build_bazel_rules_nodejs_dependencies")

build_bazel_rules_nodejs_dependencies()

load("@build_bazel_rules_nodejs//:index.bzl", "node_repositories", "yarn_install")

# want to use 18.3.0 but is currently not supported by debian 9 -> nodejs_image, watch for docker_rules updates
node_repositories(
    node_version = "16.17.1",
)

yarn_install(
    name = "npm",
    frozen_lockfile = False,
    package_json = "//:package.json",
    yarn_lock = "//:yarn.lock",
)

yarn_install(
    name = "npm_blog_frontend",
    frozen_lockfile = False,
    package_json = "//frontend/blog:package.json",
    yarn_lock = "//frontend/blog:yarn.lock",
)

load("@build_bazel_rules_nodejs//toolchains/esbuild:esbuild_repositories.bzl", "esbuild_repositories")

esbuild_repositories(npm_repository = "npm")

#################################
#             SASS             #
################################

http_archive(
    name = "io_bazel_rules_sass",
    sha256 = "beb772ac3eef7c8c1cb62c35b833300fcc099ed2b7bde59ed68ba15bab9b5757",
    strip_prefix = "rules_sass-1.54.0",
    # Make sure to check for the latest version when you install
    url = "https://github.com/bazelbuild/rules_sass/archive/1.54.0.zip",
)

load("@io_bazel_rules_sass//:defs.bzl", "sass_repositories")

sass_repositories()

#################################
#          Docker 2            #
################################
# NOTE: Placed here because container_deps requires go if placed before the go config the go setup will fail (e.g. calls )
load("@io_bazel_rules_docker//repositories:deps.bzl", container_deps = "deps")

container_deps()

load(
    "@io_bazel_rules_docker//go:image.bzl",
    _go_image_repos = "repositories",
)

_go_image_repos()

load(
    "@io_bazel_rules_docker//nodejs:image.bzl",
    _nodejs_image_repos = "repositories",
)

_nodejs_image_repos()

load(
    "@io_bazel_rules_docker//toolchains/docker:toolchain.bzl",
    docker_toolchain_configure = "toolchain_configure",
)

docker_toolchain_configure(
    name = "docker_config",
    client_config = "//:docker_client.json",
)
```

BUILD.bazel (application level)
```
load("@build_stack_rules_proto//rules:proto_compile.bzl", "proto_compile")
load("@rules_proto//proto:defs.bzl", "proto_library")
load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")

proto_library(
    name = "userservice_proto",
    srcs = ["user_service.proto"],
    visibility = ["//visibility:public"],
    deps = ["@com_google_protobuf//:timestamp_proto"],
)

go_proto_library(
    name = "userservice_go_proto",
    compilers = ["@io_bazel_rules_go//proto:go_grpc"],
    importpath = "gitlab.com/joelMuehlena/jm-web-monorepo/api/user/proto",
    proto = ":userservice_proto",
    visibility = ["//visibility:public"],
)

proto_compile(
    name = "userservice_go_compile",
    output_mappings = ["user_service.pb.go=userservice/user_service.pb.go"],
    outputs = ["user_service.pb.go"],
    plugins = ["@build_stack_rules_proto//plugin/golang/protobuf:protoc-gen-go"],
    proto = "userservice_proto",
)
```

**Comment by joelMuehlena** [comment]
So I was playing around with this again and swapped with [rules_proto_grpc](https://github.com/rules-proto-grpc/rules_proto_grpc) to check if my project works with this proto lib. After swapping out I got the same error message. Because I had the time, I started investigating further and realized the problem is rooted at the Docker lib. Eventually I move the issue there because I recognized some go related issues with the Docker lib before. However after removing the Docker sections it started working.
