### ISSUE TITLE
go rules are incompatible with bazel 0.23

### ISSUE THREAD

**Issue by Zaspire** [stackb/rules_proto#57]
deps.bzl uses old bazel_gazelle, which is incompatible with 0.23

```
ERROR: /home/zaspire/.cache/bazel/_bazel_zaspire/1010357ee0e0c546a5a0c1dee8f8184b/external/bazel_gazelle/def.bzl:80:22: Traceback (most recent call last):
	File "/home/zaspire/.cache/bazel/_bazel_zaspire/1010357ee0e0c546a5a0c1dee8f8184b/external/bazel_gazelle/def.bzl", line 57
		rule(implementation = _gazelle_runner..., <2 more arguments>)
	File "/home/zaspire/.cache/bazel/_bazel_zaspire/1010357ee0e0c546a5a0c1dee8f8184b/external/bazel_gazelle/def.bzl", line 80, in rule
		attr.label(mandatory = True, allow_single_fil..., ...")
Using cfg = "data" on an attribute is a noop and no longer supported. Please remove it. You can use --incompatible_disallow_data_transition=false to temporarily disable this check.
ERROR: /home/zaspire/.cache/bazel/_bazel_zaspire/1010357ee0e0c546a5a0c1dee8f8184b/external/grpc_ecosystem_grpc_gateway/codegenerator/BUILD.bazel:5:1: error loading package '@grpc_ecosystem_grpc_gateway//': Extension file 'def.bzl' has errors and referenced by '@grpc_ecosystem_grpc_gateway//codegenerator:go_default_library'
ERROR: /home/zaspire/.cache/bazel/_bazel_zaspire/1010357ee0e0c546a5a0c1dee8f8184b/external/grpc_ecosystem_grpc_gateway/codegenerator/BUILD.bazel:5:1: label '@grpc_ecosystem_grpc_gateway//:generators' does not refer to a package group
```

**Comment by dayfine** [comment]
Is this fixable by adding bazel_gazelle to WORKSPACE? I happen to be building a go proto with .23 as well and didn't notice this.

**Comment by Zaspire** [comment]
yes. putting it in WORKSPACE solves the issue.

**Comment by pcj** [comment]
Should be fixed, please reopen if this is still an issue.
