### ISSUE TITLE
Dart: vendor_front_end/lib/src /base/source.dart:1: Error: No such file or directory

### ISSUE THREAD

**Issue by marcguilera** [stackb/rules_proto#6]
I can't generate protobufs for Dart. This is probably a mistake on my part but I'd appreciate some help.

I have a test message and the build in the same folder:

```
syntax = "proto3";

package vehicle;

message Hello {
  string hello = 1;
}

```

```
load("@build_stack_rules_proto//dart:dart_proto_library.bzl", "dart_proto_library")
load("@io_bazel_rules_dart//dart/build_rules:core.bzl", "dart_library")

proto_library(
    name = "vehicle_proto",
    srcs = [
        "messages.proto"
    ]
)

dart_proto_library(
    name = "vechicle_grpc",
    deps = [":vehicle_proto"],
)

```

My workspace looks like this:

```
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

# Toolchains
git_repository(
    name = "bazel_toolchains",
    remote = "https://github.com/bazelbuild/bazel-toolchains.git",
    commit = "999a4d472d5bf98437ed0a108c874efcfd014f93"
)

# Protocol Buffers
git_repository(
    name = "build_stack_rules_proto",
    remote = "https://github.com/stackb/rules_proto.git",
    commit = "3ef9c0d847f9f23e8086ea1bb8c02231671beb31"
)

# Dart
git_repository(
    name = "io_bazel_rules_dart",
    remote = "https://github.com/dart-lang/rules_dart.git",
    commit = "78a4e1ba257bbe9a9d7a064c8cde8c5317059e17"
)

# Setup
load("@build_stack_rules_proto//dart:deps.bzl", "dart_grpc_compile")
dart_grpc_compile()
load("@build_stack_rules_proto//dart:deps.bzl", "dart_proto_library")
dart_proto_library()
load("@dart_pub_deps_protoc_plugin//:deps.bzl", dart_protoc_plugin_deps = "pub_deps")
dart_protoc_plugin_deps()
load("@io_bazel_rules_dart//dart/build_rules:repositories.bzl", "dart_repositories")
dart_repositories()
load("@io_bazel_rules_dart//dart/build_rules/internal:pub.bzl", "pub_repository")
pub_repository(
  name = "vendor_isolate",
  output = ".",
  package = "isolate",
  version = "2.0.2"
)
```

However attempting a build results in an error:

```
INFO: Invocation ID: d1ead863-3c54-4358-9542-b2c7bf2845c6
INFO: Analysed 3 targets (1 packages loaded, 5 targets configured).
INFO: Found 3 targets...
ERROR: /private/var/tmp/_bazel_marcguilera/10b327fd9d5413a300b42a0aa4f3edb4/external/build_stack_rules_pro
to/dart/BUILD.bazel:32:1: Building Dart VM snapshot <rule context for @build_stack_rules_proto//dart:dart_
protoc_plugin> failed (Exit 254) dart failed: error executing command external/dart_sdk/bin/dart '--packag
es=bazel-out/host/bin/external/build_stack_rules_proto/dart/dart_protoc_plugin.build/dart/dart_protoc_plug

in.packages' ... (remaining 2 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
bazel-out/host/bin/external/build_stack_rules_proto/dart/dart_protoc_plugin.build/vendor_front_end/lib/src
/base/source.dart:1: Error: No such file or directory
INFO: Elapsed time: 1.218s, Critical Path: 0.95s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

**Comment by pcj** [comment]
No, not your fault, the dart support has been tricky. Spent some time on it over the last day, should be fixed in #7.

**Comment by pcj** [comment]
Note that if your proto has rpc/service definitions, use the `dart_grpc_compile` or `dart_grpc_library` rules, not `dart_proto_library`.

**Comment by marcguilera** [comment]
Thanks for looking into this. 

Changed my workspace to:

```
workspace(name = "io_basicwindow")

load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

# Toolchains
git_repository(
    name = "bazel_toolchains",
    remote = "https://github.com/bazelbuild/bazel-toolchains.git",
    commit = "999a4d472d5bf98437ed0a108c874efcfd014f93"
)

# Protocol Buffers
git_repository(
    name = "build_stack_rules_proto",
    remote = "https://github.com/stackb/rules_proto.git",
    commit = "b74e93b3a197401da858423d2758aaf4f38be4f9"
)

# Dart
git_repository(
    name = "io_bazel_rules_dart",
    remote = "https://github.com/dart-lang/rules_dart.git",
    commit = "78a4e1ba257bbe9a9d7a064c8cde8c5317059e17"
)

# Setup proto
load("@build_stack_rules_proto//dart:deps.bzl", "dart_grpc_library")

dart_grpc_library()

# rules_go used here to compile a wrapper around the protoc-gen-grpc plugin
load("@io_bazel_rules_go//go:def.bzl", "go_rules_dependencies", "go_register_toolchains")
go_rules_dependencies()
go_register_toolchains()

load("@io_bazel_rules_dart//dart/build_rules:repositories.bzl", "dart_repositories")
dart_repositories()

load("@dart_pub_deps_protoc_plugin//:deps.bzl", dart_protoc_plugin_deps = "pub_deps")
dart_protoc_plugin_deps()

load("@dart_pub_deps_grpc//:deps.bzl", dart_grpc_deps = "pub_deps")
dart_grpc_deps()

```

And the build is:

```
package(default_visibility = ["//visibility:public"])

load("@build_stack_rules_proto//dart:dart_grpc_library.bzl", "dart_grpc_library")

dart_grpc_library(
  name = "antiv_vehicle_grpc",
  deps = [
    "//projects/feeb/backend/vehicle/proto:antiv_vehicle_proto"
  ]
)
```

Turns out I'm getting:

```
ERROR: /private/var/tmp/_bazel_marcguilera/10b327fd9d5413a300b42a0aa4f3edb4/external/io_bazel_rules_go/BUILD.bazel:18:1: in go_context_data rule @io
_bazel_rules_go//:go_context_data:
Traceback (most recent call last):
        File "/private/var/tmp/_bazel_marcguilera/10b327fd9d5413a300b42a0aa4f3edb4/external/io_bazel_rules_go/BUILD.bazel", line 18
                go_context_data(name = 'go_context_data')
        File "/private/var/tmp/_bazel_marcguilera/10b327fd9d5413a300b42a0aa4f3edb4/external/io_bazel_rules_go/go/private/context.bzl", line 310, in
_go_context_data
                _filter_options((cpp.compiler_options(features) ...)), ...)
        File "/private/var/tmp/_bazel_marcguilera/10b327fd9d5413a300b42a0aa4f3edb4/external/io_bazel_rules_go/go/private/context.bzl", line 311, in
_filter_options
                cpp.compiler_options(features)
Information about the C++ toolchain API is not accessible anymore through ctx.fragments.cpp (see --incompatible_disable_legacy_cpp_toolchain_skylark
_api on http://docs.bazel.build/versions/master/skylark/backward-compatibility.html#disable-legacy-c-configuration-api for migration notes). Use CcT

oolchainInfo instead.
ERROR: Analysis of target '//projects/feeb/backend/vehicle/service:antiv_vehicle_grpc_pb' failed; build aborted: Analysis of target '@io_bazel_rules
_go//:go_context_data' failed; build aborted
```

**Comment by pcj** [comment]
Curious what version of bazel are you on?  I'm on 19.2

**Comment by pcj** [comment]
Try ``--noincompatible_disable_legacy_cpp_toolchain_skylark_api` as mentioned in https://github.com/bazelbuild/rules_go/issues/1843

**Comment by marcguilera** [comment]
I'm on `0.20.0` installed through brew. `bazel build //... --noincompatible_disable_legacy_cpp_toolchain_skylark_api` produced the same result.

**Comment by pcj** [comment]
Closing this as the dart example appears to work on 0.25.0.
